flyway.url=jdbc:postgresql://postgres:5432/biodiscoveryai
flyway.user=bdai
flyway.password=bdai_dev_password
flyway.locations=filesystem:/flyway/sql/migrations,filesystem:/flyway/sql/seeds
flyway.schemas=public
flyway.defaultSchema=public
flyway.createSchemas=true
flyway.validateMigrationNaming=true
flyway.outOfOrder=false
flyway.cleanDisabled=false
