-- ============================================================================
-- BioDiscoveryAI Relationship Engine
-- Migration: V062__relationship_engine.sql
-- Purpose:
--   Add typed, governed, temporal relationships between universal entities,
--   enabling impact analysis, graph export, dependency tracing, and digital thread.
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS governance_kernel;

CREATE TABLE IF NOT EXISTS governance_kernel.relationship_types (
    relationship_type_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relationship_type_code     TEXT NOT NULL UNIQUE,
    relationship_type_name     TEXT NOT NULL,
    relationship_description   TEXT NOT NULL,
    inverse_relationship_code  TEXT,
    directed                   BOOLEAN NOT NULL DEFAULT true,
    transitive                 BOOLEAN NOT NULL DEFAULT false,
    regulated                  BOOLEAN NOT NULL DEFAULT false,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS governance_kernel.entity_relationships (
    entity_relationship_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relationship_type_id       UUID NOT NULL REFERENCES governance_kernel.relationship_types(relationship_type_id),
    subject_entity_id          UUID NOT NULL REFERENCES governance_kernel.governance_entities(entity_id),
    object_entity_id           UUID NOT NULL REFERENCES governance_kernel.governance_entities(entity_id),
    relationship_summary       TEXT NOT NULL,
    relationship_properties    JSONB NOT NULL DEFAULT '{}',
    confidence_score           NUMERIC(4,3) CHECK (confidence_score BETWEEN 0 AND 1),
    evidence_entity_type       TEXT,
    evidence_entity_id         TEXT,
    effective_from             TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_to               TIMESTAMPTZ,
    created_by                 TEXT NOT NULL DEFAULT current_user,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(relationship_type_id, subject_entity_id, object_entity_id, effective_from)
);

CREATE TABLE IF NOT EXISTS governance_kernel.relationship_validations (
    relationship_validation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_relationship_id     UUID NOT NULL REFERENCES governance_kernel.entity_relationships(entity_relationship_id),
    validation_status          TEXT NOT NULL CHECK (validation_status IN ('pass','fail','warning','not_reviewed')),
    validation_summary         TEXT NOT NULL,
    validated_by               TEXT NOT NULL,
    validated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    evidence_uri               TEXT,
    evidence_sha256            TEXT
);

INSERT INTO governance_kernel.relationship_types (
    relationship_type_code, relationship_type_name, relationship_description, inverse_relationship_code, directed, regulated
)
VALUES
('USES','Uses','Subject uses object.','USED_BY',true,true),
('DEPENDS_ON','Depends On','Subject depends on object.','DEPENDENCY_OF',true,true),
('GENERATED_BY','Generated By','Subject was generated by object.','GENERATED',true,true),
('APPROVED_BY','Approved By','Subject was approved by object/person.','APPROVED',true,true),
('VALIDATED_BY','Validated By','Subject was validated by object/person.','VALIDATED',true,true),
('SUPPORTS','Supports','Subject supports object, claim, submission, or decision.','SUPPORTED_BY',true,true),
('MITIGATES','Mitigates','Subject mitigates risk or issue.','MITIGATED_BY',true,true),
('SUPERSEDES','Supersedes','Subject supersedes object.','SUPERSEDED_BY',true,true)
ON CONFLICT (relationship_type_code) DO NOTHING;

CREATE OR REPLACE VIEW governance_kernel.v_entity_relationship_graph AS
SELECT
    er.entity_relationship_id,
    rt.relationship_type_code,
    s.enterprise_object_id AS subject_enterprise_object_id,
    s.canonical_name AS subject_name,
    o.enterprise_object_id AS object_enterprise_object_id,
    o.canonical_name AS object_name,
    er.relationship_summary,
    er.confidence_score,
    er.effective_from,
    er.effective_to
FROM governance_kernel.entity_relationships er
JOIN governance_kernel.relationship_types rt ON rt.relationship_type_id = er.relationship_type_id
JOIN governance_kernel.governance_entities s ON s.entity_id = er.subject_entity_id
JOIN governance_kernel.governance_entities o ON o.entity_id = er.object_entity_id;

CREATE INDEX IF NOT EXISTS idx_entity_relationships_subject
ON governance_kernel.entity_relationships(subject_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_relationships_object
ON governance_kernel.entity_relationships(object_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_relationships_type
ON governance_kernel.entity_relationships(relationship_type_id);

COMMIT;
