$base = 'C:\biodiscovery\01_foundation'
$domains = @(
  @{Id='b001_09'; Name='scientific_intelligence_services'; Title='Scientific Intelligence Services'; Summary='Ingestion, parser, NLP, ontology, graph, retrieval, embedding, ranking, arbitration, contradiction, confidence, RAG, review, export, and validation services.'; Workflow='Scientific workflow scaffold'; Root='apps/scientific-intelligence'; Components=@('ingestion-service','parser-service','nlp-service','ontology-service','graph-service','retrieval-service','embedding-service','ranking-service','arbitration-service','contradiction-service','confidence-service','rag-service','review-service','export-service','validation-service')},
  @{Id='b001_10'; Name='user_experience_layer'; Title='User Experience Layer'; Summary='Web UI, admin console, developer portal, workbench, evidence review, decision brief, graph explorer, contradiction explorer, trust center, dashboard, notebook, API console, and docs portal.'; Workflow='Experience workflow scaffold'; Root='apps/experience'; Components=@('web-ui','admin-console','developer-portal','workbench','evidence-review','decision-brief','graph-explorer','contradiction-explorer','trust-center','dashboard','notebook','api-console','docs-portal')},
  @{Id='b001_11'; Name='shared_platform_libraries'; Title='Shared Platform Libraries'; Summary='Core, schemas, security, governance, audit, observability, events, workflows, validation, graph, retrieval, and scoring SDKs.'; Workflow='Shared SDK setup'; Root='packages'; Components=@('core-sdk','schemas-sdk','security-sdk','governance-sdk','audit-sdk','observability-sdk','events-sdk','workflows-sdk','validation-sdk','graph-sdk','retrieval-sdk','scoring-sdk')},
  @{Id='b001_12'; Name='enterprise_domain_layer'; Title='Enterprise Domain Layer'; Summary='Seventeen-domain architecture map from product strategy through corporate governance.'; Workflow='Domain architecture setup'; Root='domains'; Components=@('product-strategy','scientific-intelligence','data-foundation','core-platform','security','governance-compliance','clinical-regulatory','engineering','runtime-operations','customer-experience','commercial','finance','legal','people-operations','partner-ecosystem','research-frontier','corporate-governance')},
  @{Id='b001_13'; Name='contracts_interfaces'; Title='Contracts & Interfaces'; Summary='OpenAPI, Protobuf, event schemas, JSON Schema, graph contracts, and policy contracts.'; Workflow='Contract-first setup'; Root='contracts'; Components=@('openapi','protobuf','event-schemas','json-schema','graph-contracts','policy-contracts')},
  @{Id='b001_14'; Name='data_foundation'; Title='Data Foundation'; Summary='Seed data, fixtures, goldsets, evidence snapshots, graph snapshots, and private data marker.'; Workflow='Data foundation setup'; Root='data'; Components=@('seed-data','fixtures','goldsets','evidence-snapshots','graph-snapshots','private-data-marker')},
  @{Id='b001_15'; Name='data_integration_substrate'; Title='Data & Integration Substrate'; Summary='PubMed, ClinicalTrials, FDA, EHR, lab omics connector lanes, evidence lake, feature store, vector store, graph store, and metadata catalog.'; Workflow='Data connector setup'; Root='integrations/data-substrate'; Components=@('pubmed-connector','clinicaltrials-connector','fda-connector','ehr-connector','lab-omics-connector','evidence-lake','feature-store','vector-store','graph-store','metadata-catalog')},
  @{Id='b001_16'; Name='integration_layer'; Title='Integration Layer'; Summary='API gateway, event gateway, webhook gateway, customer-private connectors, and partner connectors.'; Workflow='External integration setup'; Root='integrations/external'; Components=@('api-gateway','event-gateway','webhook-gateway','customer-private-connectors','partner-connectors')},
  @{Id='b001_17'; Name='orchestration_layer'; Title='Orchestration Layer'; Summary='Workflow, model, and agent orchestration; routing, queues, distributed execution, batch, stream, events, pipeline, and lineage.'; Workflow='Runtime orchestration setup'; Root='orchestration'; Components=@('workflow-orchestration','model-orchestration','agent-orchestration','routing','queues','distributed-execution','batch-runtime','stream-runtime','event-runtime','pipeline-runtime','lineage')},
  @{Id='b001_18'; Name='intelligence_layer'; Title='Intelligence Layer'; Summary='Trust science, graph intelligence, validation science, runtime safety, provenance, temporal intelligence, memory, digital twin, autonomous science, and causal intelligence.'; Workflow='AI/science intelligence setup'; Root='intelligence'; Components=@('trust-science','graph-intelligence','validation-science','runtime-safety','provenance','temporal-intelligence','memory','digital-twin','autonomous-science','causal-intelligence')},
  @{Id='b001_19'; Name='governance_layer'; Title='Governance Layer'; Summary='Policy engine, authorization, inference and output governance, auditability, compliance, and liability boundaries.'; Workflow='Governance runtime setup'; Root='governance'; Components=@('policy-engine','authorization','inference-governance','output-governance','auditability','compliance','liability-boundaries')},
  @{Id='b001_20'; Name='security_layer'; Title='Security Layer'; Summary='Zero trust, containment, supply chain, DLP, and biosecurity boundaries.'; Workflow='Security architecture setup'; Root='security'; Components=@('zero-trust','containment','supply-chain','dlp','biosecurity-boundaries')},
  @{Id='b001_21'; Name='platform_infrastructure'; Title='Platform Infrastructure'; Summary='Docker, Kubernetes, Helm, Terraform, Argo CD, OPA, Gatekeeper, secrets, and network policies.'; Workflow='Infrastructure setup'; Root='infrastructure'; Components=@('docker','kubernetes','helm','terraform','argo-cd','opa','gatekeeper','secrets','network-policies')},
  @{Id='b001_22'; Name='runtime_persistence'; Title='Runtime Persistence'; Summary='Postgres, Neo4j, and OpenSearch migration folders and baseline migrations.'; Workflow='Persistence setup'; Root='persistence'; Components=@('postgres','neo4j','opensearch')},
  @{Id='b001_23'; Name='observability_reliability'; Title='Observability & Reliability'; Summary='Prometheus, Grafana, OpenTelemetry, alerts, observability service, and logging placeholder.'; Workflow='Observability setup'; Root='observability'; Components=@('prometheus','grafana','opentelemetry','alerts','observability-service','logging')},
  @{Id='b001_24'; Name='validation_assurance'; Title='Validation & Assurance'; Summary='Validation service, tests, eval harness, goldsets, citation integrity, hallucination, contradiction, reviewer calibration, and regression.'; Workflow='Validation setup'; Root='validation'; Components=@('validation-service','tests','eval-harness','goldsets','citation-integrity','hallucination','contradiction','reviewer-calibration','regression')},
  @{Id='b001_25'; Name='operations_layer'; Title='Operations Layer'; Summary='SRE, incident management, disaster recovery, capacity planning, and cost governance.'; Workflow='Operations setup'; Root='operations'; Components=@('sre','incident-management','disaster-recovery','capacity-planning','cost-governance')},
  @{Id='b001_26'; Name='commercial_layer'; Title='Commercial Layer'; Summary='Customer success, revenue operations, procurement, partner program, and market intelligence.'; Workflow='Commercial ops setup'; Root='commercial'; Components=@('customer-success','revenue-operations','procurement','partner-program','market-intelligence')},
  @{Id='b001_27'; Name='frontier_future_science_layer'; Title='Frontier / Future Science Layer'; Summary='Multi-omics, causal AI, digital twins, simulation engine, federated intelligence, and autonomous science.'; Workflow='Future science setup'; Root='frontier'; Components=@('multi-omics','causal-ai','digital-twins','simulation-engine','federated-intelligence','autonomous-science')},
  @{Id='b001_28'; Name='registries'; Title='Registries'; Summary='Models, prompts, datasets, benchmarks, ontologies, workflows, scoring, evidence, graph snapshots, policies, tools, agents, connectors, and simulations.'; Workflow='Registry control-plane setup'; Root='registries'; Components=@('models','prompts','datasets','benchmarks','ontologies','workflows','scoring','evidence','graph-snapshots','policies','tools','agents','connectors','simulations')},
  @{Id='b001_29'; Name='plugin_architecture'; Title='Plugin Architecture'; Summary='Reasoning engines, data connectors, model providers, scoring modules, validation modules, export formats, safety controls, and simulations.'; Workflow='Plugin substrate setup'; Root='plugins'; Components=@('reasoning-engines','data-connectors','model-providers','scoring-modules','validation-modules','export-formats','safety-controls','simulations')},
  @{Id='b001_30'; Name='extension_points'; Title='Extension Points'; Summary='Events, workflows, claims, scoring, retrieval, graph, governance, and UI extension interfaces.'; Workflow='Extension interface setup'; Root='extension-points'; Components=@('events','workflows','claims','scoring','retrieval','graph','governance','ui')},
  @{Id='b001_31'; Name='documentation_governance_docs'; Title='Documentation & Governance Docs'; Summary='README, changelog, license, security, governance, compliance, ADR, principles, intended use, risk register, review state machine, policies, privacy, validation, twin readiness, and procurement.'; Workflow='Documentation generation'; Root='docs'; Components=@('readme','changelog','license','security','governance','compliance','adr','principles','intended-use','risk-register','review-state-machine','policies','privacy','validation','twin-readiness','procurement')},
  @{Id='b001_32'; Name='architecture_documentation'; Title='Architecture Documentation'; Summary='OS substrate, domain-layer map, extension-points doc, and registry strategy.'; Workflow='Architecture documentation'; Root='docs/architecture'; Components=@('os-substrate','domain-layer-map','extension-points','registry-strategy')},
  @{Id='b001_33'; Name='policy_as_code'; Title='Policy-as-Code'; Summary='OPA source policy, export policy, and no-citation-no-claim policy.'; Workflow='Policy foundation setup'; Root='policies'; Components=@('opa-source-policy','export-policy','no-citation-no-claim-policy')},
  @{Id='b001_34'; Name='service_template_generator'; Title='Service Template & Generator'; Summary='Service template README, FastAPI health app, Dockerfile, tests, and service generator.'; Workflow='Service factory setup'; Root='tools/service-factory'; Components=@('service-template-readme','fastapi-health-app','dockerfile','tests','service-generator')},
  @{Id='b001_35'; Name='developer_tooling'; Title='Developer Tooling'; Summary='.gitignore, .dockerignore, .editorconfig, .env.example, pyproject.toml, and Makefile.'; Workflow='Developer environment setup'; Root='.'; Components=@('gitignore','dockerignore','editorconfig','env-example','pyproject-toml','makefile')},
  @{Id='b001_36'; Name='cicd'; Title='CI/CD'; Summary='GitHub Actions foundation CI workflow.'; Workflow='CI/CD setup'; Root='.github/workflows'; Components=@('foundation-ci')},
  @{Id='b001_37'; Name='foundation_validation'; Title='Foundation Validation'; Summary='Validation container, validation script, basic tests, and Docker/local validation when executed.'; Workflow='Validation execution'; Root='foundation-validation'; Components=@('validation-container','validation-script','basic-tests','docker-validation','local-validation')},
  @{Id='b001_38'; Name='script_registry_reporting'; Title='Script Registry & Reporting'; Summary='Script registry, generated script marker, and FOUNDATION_REPORT.md.'; Workflow='Build ledger / reporting'; Root='.foundation/registry'; Components=@('script-registry','generated-script-marker','foundation-report')},
  @{Id='b001_39'; Name='next_step_guidance'; Title='Next-Step Guidance'; Summary='Prints next commands and recommends next implementation step.'; Workflow='Handoff / next-step guidance'; Root='.foundation/next-steps'; Components=@('next-commands','implementation-recommendations','handoff-guidance')}
)

$templatePath = Join-Path $PSScriptRoot 'templates\b001_domain_script.template.sh'
$template = [System.IO.File]::ReadAllText($templatePath)

foreach ($d in $domains) {
  $fileName = "$($d.Id)_$($d.Name).sh"
  $componentLines = ($d.Components | ForEach-Object { "  `"$_|Scaffold boundary for $_ within $($d.Title).`"" }) -join "`n"
  $content = $template
  $content = $content.Replace('@SCRIPT_ID@', $d.Id)
  $content = $content.Replace('@SCRIPT_NAME@', $d.Name.Replace('_','-'))
  $content = $content.Replace('@TITLE@', $d.Title)
  $content = $content.Replace('@SUMMARY@', $d.Summary)
  $content = $content.Replace('@WORKFLOW@', $d.Workflow)
  $content = $content.Replace('@ROOT@', $d.Root)
  $content = $content.Replace('@EVIDENCE_NAME@', $d.Name)
  $content = $content.Replace('@FILE_NAME@', $fileName)
  $content = $content.Replace('@COMPONENT_LINES@', $componentLines)
  [System.IO.File]::WriteAllText((Join-Path $base $fileName), $content, [System.Text.UTF8Encoding]::new($false))
  Write-Output "Wrote $fileName"
}
